import React from 'react'

const data = [
    {
        profile_image:"https://scontent.fdel9-1.fna.fbcdn.net/v/t1.0-0/p640x640/66278041_120821215857588_1518197185957593088_o.jpg?_nc_cat=111&_nc_sid=e3f864&_nc_ohc=kjgYT_-zbY8AX-8iiJv&_nc_ht=scontent.fdel9-1.fna&_nc_tp=6&oh=67756ac5d1aed2558e9ace5413a6976f&oe=5F2BB73E",
        name:"Ayush Singh",
        designation:"Front-End",
        phone:"8860822471",
        hostel:"Satpura",
        email:"singhayush4499@gmail.com",
        website:"www.github.com/webster-781",
        bio:"I like Maths and doing cool stuff with programming. I like to play chess, play drums and reading novels.",
    },
    {
        image_source:require('../assets/ayush-verma.jpg'),
        profile_image:"",
        name:"Ayush Verma",
        designation:"Backend Developer",
        phone:"",
        hostel:"Kumaon",
        email:"vermakabir.ayush@gmail.com",
        website:"",
        bio:"Making the world better, one innovation at a time. Like to make things which touches the daily life of people. I love cinema, coffee and memes.",
    },
    {
        profile_image:"https://scontent.fjai1-1.fna.fbcdn.net/v/t1.0-9/58375242_2081506201904930_8934704076550045696_n.jpg?_nc_cat=109&_nc_sid=09cbfe&_nc_oc=AQl80pGXkIMg711IYD-hRipXjr3ntSYenNNAyttgdy0MfcXMaCM7588Rn6281VIhWJ58snMxaMtvuNVkuHfOOESH&_nc_ht=scontent.fjai1-1.fna&oh=c7a5bdeb569421472bce75ed0821de94&oe=5F2994B4",
        name:"Mudit Garg",
        designation:"Frontend Developer",
        phone:"6350385896",
        hostel:"Satpura",
        email:"mboxmudit@gmail.com",
        website:"",
        bio:"Sarcastic, Curious, Rational, Always ready to help. Love scientific discussions. Late night fun group chat with friends, mocking each other, makes my day.",
    },
    {
        image_source:require('../assets/harshit-abrol.jpg'),
        profile_image:"",
        name:"Harshit Abrol",
        designation:"Design",
        phone:"",
        hostel:"",
        email:"",
        website:"",
        bio:"I was involved in curating the design features of the application.",        
    },
    {
        image_source:require('../assets/rahul-parmar.jpg'),
        profile_image:"",
        name:"Rahul Parmar",
        designation:"Backend Developer",
        phone:"9340264329",
        hostel:"",
        email:"rahul220.iit@gmail.com",
        website:"www.github.com/ramrap",
        bio:"Yo Guys !! \n Rahul here, UG student of CSE , Tech Enthusiast with no Technical Knowledge 🤫.",
    },
    {
        image_source:require('../assets/shantanu-verma.jpeg'),
        profile_image:"",
        name:"Shantanu Verma",
        designation:"Backend Developer",
        phone:"",
        hostel:"Kumaon",
        email:"",
        website:"www.github.com/shantanuv12",
        bio:"God is real, unless declared integer",
    },
    {
        image_source:require('../assets/shubham-attri.jpeg'),
        profile_image:"",
        name:"Shubham Attri",
        designation:"Backend Developer",
        phone:"",
        hostel:"Kumaon",
        email:"sattri12@gmail.com",
        website:"",
        bio:"Experienced Computer Science Specialist with a demonstrated history of working in the higher education and finance industry. Skilled in Python (Programming Language), C++, Artificial Intelligence (AI), Java, JS and Machine Learning.",
    },
]

export default data;